# READ FIRST: Please set all settings marked with the following character! #{***}
# Set the path to the folder where your files are located! #{***}
sample_path: /home/datasets/analyze/
# Set the project name for your samples; Example: drosophila_samples;
# This will create a subfolder in 'results' with the project name you entered. 
# The folder contains a text file with the names of your samples.
project_name: Plasmodium_SMPLS
# Canu; Set genomeSize; genomeSize={params.canu_genome_size}; 
# Determine the size of your genome! #{***}
canu_genome_size: "23m"
# Canu; Set minInputCoverage; minInputCoverage={params.canu_minInputCoverage};
# If you do not add minInputCoverage (canu_minInputCoverage: ""), current coverage of the sample is always used!
canu_minInputCoverage: ""
# Canu; Set stopOnLowCoverage; stopOnLowCoverage={params.canu_stopOnLowCoverage};
# If you do not add stopOnLowCoverage (canu_stopOnLowCoverage: ""), current coverage of the sample is always used!
canu_stopOnLowCoverage: ""
# Canu; Set useGrid(true/false); useGrid={params.canu_grid};
# Cluster analyses;
canu_grid: "false"
# BUSCO; Set mode; mode=config["busco_mode"];
# Leave unchanged when analyzing genomes! #{***}
busco_mode: "genome"
# BUSCO; lineage; extra=config["busco_lineage"];
# For a specific eukaryotic organism; https://busco.ezlab.org/list_of_lineages.html; 
busco_lineage: "eukaryota_odb10"
# FASTQC; Set memory; 
# Example(use of 8GB): fastqc_memory: "8192"; #{***}
# If you do not want to use a specific memory, you should leave the field empty; fastqc_memory: ""
fastqc_memory: ""